name: CI/CD para Kubernetes (Main)

on:
  push:
    branches:
      - main

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

     # - name: Rodar testes com Maven
      #  run: mvn clean test -X -f back/pom.xml

      - name: Build da imagem Docker
        run: |
          docker build -t regiinaldo/back-gurudoamor:latest ./back

      - name: Login no Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push da imagem para o Docker Hub
        run: |
          docker push regiinaldo/back-gurudoamor:latest

      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Instalar gcloud + kubectl
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: desafio-pipeline
          install_components: 'kubectl'
          export_default_credentials: true

      - name: Acessar cluster do GKE
        run: |
          gcloud container clusters get-credentials desafio-pipeline-01 \
            --zone us-central1 \
            --project desafio-pipeline

      - name: Aplicar manifests no namespace production
        run: |
          kubectl apply -f k8s/production/ --namespace=production

      - name: Forçar reinício dos pods (caso necessário)
        run: |
          kubectl rollout restart deployment/backend -n production
